version: '3'

services:
  auth_database:
    image: postgres:13.0
    restart: always
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./config/auth/.env.prod.db
    command: -p 6432
    expose:
      - 6432

  auth_service:
    build:
      context: ../src
      dockerfile: Dockerfile
    depends_on:
      - auth_database
      - auth_redis
      - refresh_auth_redis
    env_file:
      - ./config/auth/.env.prod.test

  auth_redis:
    image: redis:latest
    restart: always
    command: --port 6381
    expose:
      - 6381
    env_file:
      - ./config/auth/.env.prod.test

  refresh_auth_redis:
    image: redis:latest
    restart: always
    command: --port 6380
    expose:
      - 6380
    env_file:
      - ./config/auth/.env.prod.test

  rate_limit_redis:
    image: redis:latest
    restart: always
    command: --port 6382
    expose:
      - 6382
    env_file:
      - ./config/auth/.env.prod.test

  auth_test:
    build:
      context: ../tests/functional
      dockerfile: Dockerfile
    depends_on:
      - auth_service
    env_file:
      - ./config/auth/.env.prod.test

  oauth_redis:
    image: redis:latest
    restart: always
    command: --port 6383
    expose:
      - 6383
    env_file:
      - ./config/auth/.env.prod.test

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 16686:16686

  nginx:
    image: nginx:latest
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/configs:/etc/nginx/conf.d:ro
      - static_volume:/opt/app/staticfiles
      - media_volume:/opt/app/mediafiles
    environment:
      NGINX_SET_REAL_IPS_FROM: "[\"192.168.1.0/24\"]"
    depends_on:
      - auth_service
    ports:
      - 80:80

volumes:
  static_volume:
  media_volume:
  auth_postgres_data: