version: '3'

services:
  service:
    image: mistandok/online-cinema-admin-panel:v1.0.1
    volumes:
      - static_volume:/opt/app/staticfiles
      - media_volume:/opt/app/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./config/admin_panel/.env.prod
    depends_on:
      - database

  database:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./config/admin_panel/.env.prod.db

  etl:
    image: mistandok/online-cinema-etl-process:v2.0.1
    env_file:
      - ./config/etl_process/.env.prod
    depends_on:
      - database
      - elasticsearch
      - redis
    restart: always

  elasticsearch:
    image: elasticsearch:8.5.3
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms6g -Xmx6g
      USE_SSL: false
      xpack.security.enabled: false
      cluster.routing.allocation.disk.threshold_enabled: false

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  fastapi:
    image: zhetonmoveton/fastapi:1.0.0
    restart: always
    env_file:
      - ./config/fastapi_project/.env.prod
    depends_on:
      - redis
      - elasticsearch

  auth_database:
    image: postgres:13.0
    restart: always
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./config/auth/.env.prod.db
    command: -p 6432
    ports:
      - 6432:6432

  auth_service:
#    image: mistandok/auth-service:v2.0.0
    build:
      context: ../src
      dockerfile: Dockerfile
    depends_on:
      - auth_database
      - auth_redis
      - refresh_auth_redis
    env_file:
      - ./config/auth/.env.prod.dev

  auth_redis:
    image: redis:latest
    restart: always
    command: --port 6381
    ports:
      - 6381:6381
    env_file:
      - ./config/auth/.env.prod.dev

  refresh_auth_redis:
    image: redis:latest
    restart: always
    command: --port 6380
    ports:
      - 6380:6380
    env_file:
      - ./config/auth/.env.prod.dev

  rate_limit_redis:
    image: redis:latest
    restart: always
    command: --port 6382
    ports:
      - 6382:6382
    env_file:
      - ./config/auth/.env.prod.dev

  nginx:
    image: nginx:latest
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/configs:/etc/nginx/conf.d:ro
      - static_volume:/opt/app/staticfiles
      - media_volume:/opt/app/mediafiles
    environment:
      NGINX_SET_REAL_IPS_FROM: "[\"192.168.1.0/24\"]"
    depends_on:
      - fastapi
      - service
      - auth_service
    ports:
      - 80:80

  oauth_redis:
    image: redis:latest
    restart: always
    command: --port 6383
    ports:
      - 6383:6383
    env_file:
      - ./config/auth/.env.prod.dev

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 16686:16686

volumes:
  postgres_data:
  static_volume:
  media_volume:
  auth_postgres_data: